### ISSUE TITLE
"ReferenceError: _ is not defined" in Meteor 1.7

### ISSUE THREAD

**Issue by thoni56** [rafaelhdr/meteor-google-charts#11]
This is due to Meteor no longer providing Underscore per default. See [the thread in the forum](https://forums.meteor.com/t/referenceerror-is-not-defined-how-to-fix/44038) for some info.

**Comment by thoni56** [comment]
I suppose adding a dependency to `underscore` in `package.js` should suffice:

    Package.onUse((api) => {
        api.use('underscore');
        ...

**Comment by rafaelhdr** [comment]
Thanks @thoni56 

Updated to `0.0.9`. I think it is ok now, but re-open if not.
