### ISSUE TITLE
"meteor add" command downloads original version of package from Atmospherejs

### ISSUE THREAD

**Issue by Moonmarsh** [rafaelhdr/meteor-google-charts#2]
Finally got around to attempting to use this package via atmosphere today. Notices that the version downloaded is missing the "timeline" addition.

Wondering if something else needs to be changed for this new version of the package to be recognised on atmosphere? I noticed that I did not make any changes to packages.json when I did the PR.  Do you think package.json should also be bumped up with a new version number?

Kind regards
James

**Comment by rafaelhdr** [comment]
Thanks :)
I think it is updated on Atmosphere. I Edited the version number to 0.0.2, and published.

Is it working fine?

**Comment by Moonmarsh** [comment]
Yes working fine now. 

Thanks
