### ISSUE TITLE
failed to install packages under Windows

### ISSUE THREAD

**Issue by domislo1** [rafaelhdr/meteor-google-charts#5]
Hello, I am running Meteor 1.4 under Windows10 64 bits edition. 

The installation of the package simple failed even if I run the command with the administrator rights.  
That works fine under linux plateforme

C:\Users\Domi\Documents\meteor\testdb>meteor add rafaelhdr:google-charts
C:\Users\Domi\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Domi\AppData\Local\Temp\mt-toqi9g\os\rafaelhdr:google-charts.js'
    at Error (native)

is the module compliant with windows ?

thx

**Comment by rafaelhdr** [comment]
Hello @domislo1 

Sorry. I didn't test on Windows. Only on Ubuntu.

But i've just fixed on commits:
- https://github.com/rafaelhdr/meteor-google-charts/commit/61ff6476db0b631b6313f62132150171af8ffb8b
- https://github.com/rafaelhdr/meteor-google-charts/commit/b3509687342ed07b2b6e301e2d1d977f07f7ac09

If you try again add it, i think it will work fine.

# About the problem

Windows does not accept colon (**:**) on file name. It changes to underscore (**_**). So, it renamed the files, and didn't find on _addFiles_.

Thanks for the help

**Comment by domislo1** [comment]
wonderfull, works perfectly.
Many thanks, 

```
Le Samedi 1 octobre 2016 20h50, Rafael <notifications@github.com> a écrit :
```

 Hello @domislo1 Sorry. I didn't test on Windows. Only on Ubuntu.But i've just fixed on commits:   
- 61ff647
- b350968
  If you try again add it, i think it will work fine.
  About the problem
  Windows does not accept colon (:) on file name. It changes to underscore (_). So, it renamed the files, and didn't find on addFiles.Thanks for the help—
