### ISSUE TITLE
Charts are not being rendered in Google Chrome 

### ISSUE THREAD

**Issue by mostafiz93** [rafaelhdr/meteor-google-charts#7]
I've installed this plugin via atmospherejs. But after installation I can't render charts. The error shown in console is:

> A Parser-blocking, cross-origin script, https://www.google.com/uds/?file=visualization&v=1.0&packages=corechart%2Cgauge%2Ctimeline, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

**Comment by rafaelhdr** [comment]
Hello @mostafiz93 

This is the same problem of issue https://github.com/rafaelhdr/meteor-google-charts/issues/6 , right?

Please, join our conversation there :)
