### ISSUE TITLE
Please add a license so that others can use this package

### ISSUE THREAD

**Issue by levinse** [rafaelhdr/meteor-google-charts#8]
Could you please add a license so that others can use this package? Publishing software without a license means that anyone attempting to use it would be in violation of copyright. If you could please add a MIT or other distribution-friendly license, that would be appreciated!

Thanks

**Comment by rafaelhdr** [comment]
Hello,

Thanks for the suggestion.
I've never done this before. Do you have any recommendation for it?

Thanks
