### ISSUE TITLE
Does not support dynamic chart creation

### ISSUE THREAD

**Issue by stevehickman** [rafaelhdr/meteor-google-charts#9]
The call to Google Charts only occurs in loadScript. As a result, it does not support creation of charts after the page has loaded.

Solution: All you need to do is take the second definition of drawChart (the one that actually does all the work) and define it outside of the loadScript function (you'll need to rename one of the drawCharts to avoid name collisions). Then that function can be called at any time.

**Comment by rafaelhdr** [comment]
Thanks for the help. Really busy here, but ASAP i will check it (i think i can see it better on weekend).

**Comment by rafaelhdr** [comment]
@stevehickman Thank you very much. With your solution, could solve it easily :)

Solved at version 0.0.8 2624b2b5d0fa3c5425d26db139a28dd1b48dee58
